### ISSUE TITLE
Errors after upgrading to gradle version 4.6

### ISSUE THREAD

**Issue by STG284** [i-am-g2/Advitiya#1]
Errors:

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:mergeDebugResources'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.internal.UncheckedException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
Output:  W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1055: error: unescaped apostrophe in string
"A large number of things can be made from microcontrollers just by utilizing the vast potential of the sensors available in the market. A simple atmega chip packs the potential to make millions of things.But time doesn\'t permits this. So, you need to design the solution packed with innovation,knowledge and energy to work on a problem statement given in-situ within 24 hours. So get packed up challenge isn't that easy.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1055: error: not a valid string.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1070: error: unescaped apostrophe in string
""Life is not always a matter of holding good cards, but sometimes, playing a poor hand well."\n
"Poker Night" offers a host of tournaments for enthusiasts to play poker. Come, show your poker strategy and embark on your journey to becoming a poker pro. Don't forget to register yor name and win a chance to grab exciting prizes.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1068: error: not a valid string.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1077: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1087: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1096: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.

Command: C:\Users\verma\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\3d7d177b79243c50fc8d502ac8f46ca0\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\res\merged\debug \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
Output:  W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:90:5-459: AAPT: error: unescaped apostrophe in string
    
"A large number of things can be made from microcontrollers just by utilizing the vast potential of the sensors available in the market. A simple atmega chip packs the potential to make millions of things.But time doesn\'t permits this. So, you need to design the solution packed with innovation,knowledge and energy to work on a problem statement given in-situ within 24 hours. So get packed up challenge isn't that easy.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:90:5-459: AAPT: error: not a valid string.
    
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\generated\res\google-services\debug\values\values.xml:10:5-72: AAPT: error: unescaped apostrophe in string
    
""Life is not always a matter of holding good cards, but sometimes, playing a poor hand well."\n
"Poker Night" offers a host of tournaments for enthusiasts to play poker. Come, show your poker strategy and embark on your journey to becoming a poker pro. Don't forget to register yor name and win a chance to grab exciting prizes.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:98:5-100:10: AAPT: error: not a valid string.
    
W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:17:5-112: AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
    
W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:39:5-105: AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
    
W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:18:5-117: AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
    
Command: C:\Users\verma\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\3d7d177b79243c50fc8d502ac8f46ca0\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\res\merged\debug \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	... 33 more
Caused by: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
Output:  W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1055: error: unescaped apostrophe in string
"A large number of things can be made from microcontrollers just by utilizing the vast potential of the sensors available in the market. A simple atmega chip packs the potential to make millions of things.But time doesn\'t permits this. So, you need to design the solution packed with innovation,knowledge and energy to work on a problem statement given in-situ within 24 hours. So get packed up challenge isn't that easy.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1055: error: not a valid string.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1070: error: unescaped apostrophe in string
""Life is not always a matter of holding good cards, but sometimes, playing a poor hand well."\n
"Poker Night" offers a host of tournaments for enthusiasts to play poker. Come, show your poker strategy and embark on your journey to becoming a poker pro. Don't forget to register yor name and win a chance to grab exciting prizes.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1068: error: not a valid string.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1077: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1087: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1096: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.

Command: C:\Users\verma\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\3d7d177b79243c50fc8d502ac8f46ca0\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\res\merged\debug \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
Output:  W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:90:5-459: AAPT: error: unescaped apostrophe in string
    
"A large number of things can be made from microcontrollers just by utilizing the vast potential of the sensors available in the market. A simple atmega chip packs the potential to make millions of things.But time doesn\'t permits this. So, you need to design the solution packed with innovation,knowledge and energy to work on a problem statement given in-situ within 24 hours. So get packed up challenge isn't that easy.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:90:5-459: AAPT: error: not a valid string.
    
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\generated\res\google-services\debug\values\values.xml:10:5-72: AAPT: error: unescaped apostrophe in string
    
""Life is not always a matter of holding good cards, but sometimes, playing a poor hand well."\n
"Poker Night" offers a host of tournaments for enthusiasts to play poker. Come, show your poker strategy and embark on your journey to becoming a poker pro. Don't forget to register yor name and win a chance to grab exciting prizes.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:98:5-100:10: AAPT: error: not a valid string.
    
W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:17:5-112: AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
    
W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:39:5-105: AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
    
W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:18:5-117: AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
    
Command: C:\Users\verma\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\3d7d177b79243c50fc8d502ac8f46ca0\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\res\merged\debug \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.android.ide.common.workers.ExecutorServiceAdapter.close(ExecutorServiceAdapter.kt:56)
	at com.android.build.gradle.internal.aapt.WorkerExecutorResourceCompilationService.close(WorkerExecutorResourceCompilationService.kt:67)
	at com.android.build.gradle.tasks.MergeResources.doFullTaskAction(MergeResources.java:324)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	... 43 more
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
Output:  W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1055: error: unescaped apostrophe in string
"A large number of things can be made from microcontrollers just by utilizing the vast potential of the sensors available in the market. A simple atmega chip packs the potential to make millions of things.But time doesn\'t permits this. So, you need to design the solution packed with innovation,knowledge and energy to work on a problem statement given in-situ within 24 hours. So get packed up challenge isn't that easy.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1055: error: not a valid string.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1070: error: unescaped apostrophe in string
""Life is not always a matter of holding good cards, but sometimes, playing a poor hand well."\n
"Poker Night" offers a host of tournaments for enthusiasts to play poker. Come, show your poker strategy and embark on your journey to becoming a poker pro. Don't forget to register yor name and win a chance to grab exciting prizes.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1068: error: not a valid string.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1077: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1087: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1096: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.

Command: C:\Users\verma\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\3d7d177b79243c50fc8d502ac8f46ca0\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\res\merged\debug \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
Output:  W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:90:5-459: AAPT: error: unescaped apostrophe in string
    
"A large number of things can be made from microcontrollers just by utilizing the vast potential of the sensors available in the market. A simple atmega chip packs the potential to make millions of things.But time doesn\'t permits this. So, you need to design the solution packed with innovation,knowledge and energy to work on a problem statement given in-situ within 24 hours. So get packed up challenge isn't that easy.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:90:5-459: AAPT: error: not a valid string.
    
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\generated\res\google-services\debug\values\values.xml:10:5-72: AAPT: error: unescaped apostrophe in string
    
""Life is not always a matter of holding good cards, but sometimes, playing a poor hand well."\n
"Poker Night" offers a host of tournaments for enthusiasts to play poker. Come, show your poker strategy and embark on your journey to becoming a poker pro. Don't forget to register yor name and win a chance to grab exciting prizes.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:98:5-100:10: AAPT: error: not a valid string.
    
W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:17:5-112: AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
    
W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:39:5-105: AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
    
W:\My Projects\AndroidStudioProjects\Advitiya\app\src\main\res\values\strings.xml:18:5-117: AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
    
Command: C:\Users\verma\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\3d7d177b79243c50fc8d502ac8f46ca0\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\res\merged\debug \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteException(Aapt2ErrorUtils.kt:97)
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteCompileException(Aapt2ErrorUtils.kt:55)
	at com.android.build.gradle.internal.res.Aapt2CompileWithBlameRunnable$run$1.invoke(Aapt2CompileWithBlameRunnable.kt:39)
	at com.android.build.gradle.internal.res.Aapt2CompileWithBlameRunnable$run$1.invoke(Aapt2CompileWithBlameRunnable.kt:28)
	at com.android.build.gradle.internal.res.namespaced.Aapt2DaemonManagerService.useAaptDaemon(Aapt2DaemonManagerService.kt:71)
	at com.android.build.gradle.internal.res.namespaced.Aapt2DaemonManagerService.useAaptDaemon$default(Aapt2DaemonManagerService.kt:69)
	at com.android.build.gradle.internal.res.Aapt2CompileWithBlameRunnable.run(Aapt2CompileWithBlameRunnable.kt:34)
	at com.android.ide.common.workers.ExecutorServiceAdapter$submit$submission$1.run(ExecutorServiceAdapter.kt:39)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
Output:  W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1055: error: unescaped apostrophe in string
"A large number of things can be made from microcontrollers just by utilizing the vast potential of the sensors available in the market. A simple atmega chip packs the potential to make millions of things.But time doesn\'t permits this. So, you need to design the solution packed with innovation,knowledge and energy to work on a problem statement given in-situ within 24 hours. So get packed up challenge isn't that easy.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1055: error: not a valid string.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1070: error: unescaped apostrophe in string
""Life is not always a matter of holding good cards, but sometimes, playing a poor hand well."\n
"Poker Night" offers a host of tournaments for enthusiasts to play poker. Come, show your poker strategy and embark on your journey to becoming a poker pro. Don't forget to register yor name and win a chance to grab exciting prizes.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1068: error: not a valid string.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1077: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1087: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1096: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.

Command: C:\Users\verma\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\3d7d177b79243c50fc8d502ac8f46ca0\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\res\merged\debug \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
	at com.android.builder.internal.aapt.v2.Aapt2DaemonImpl.doCompile(Aapt2DaemonImpl.kt:142)
	at com.android.builder.internal.aapt.v2.Aapt2Daemon.compile(Aapt2Daemon.kt:81)
	at com.android.builder.internal.aapt.v2.Aapt2DaemonManager$LeasedAaptDaemon.compile(Aapt2DaemonManager.kt:170)
	at com.android.build.gradle.internal.res.Aapt2CompileWithBlameRunnable$run$1.invoke(Aapt2CompileWithBlameRunnable.kt:37)
	... 10 more

**Comment by STG284** [comment]
Android resource compilation failed
Output:  W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1055: error: unescaped apostrophe in string
"A large number of things can be made from microcontrollers just by utilizing the vast potential of the sensors available in the market. A simple atmega chip packs the potential to make millions of things.But time doesn\'t permits this. So, you need to design the solution packed with innovation,knowledge and energy to work on a problem statement given in-situ within 24 hours. So get packed up challenge isn't that easy.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1055: error: not a valid string.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1070: error: unescaped apostrophe in string
""Life is not always a matter of holding good cards, but sometimes, playing a poor hand well."\n
"Poker Night" offers a host of tournaments for enthusiasts to play poker. Come, show your poker strategy and embark on your journey to becoming a poker pro. Don't forget to register yor name and win a chance to grab exciting prizes.".
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1068: error: not a valid string.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1077: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1087: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1096: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.

Command: C:\Users\verma\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\3d7d177b79243c50fc8d502ac8f46ca0\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\res\merged\debug \
        W:\My Projects\AndroidStudioProjects\Advitiya\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

**Comment by STG284** [comment]
Problem Resolved:

Removed stray "character at line no 98

<string name="poker">Life is not always a matter of holding good cards, but sometimes, playing a poor hand well.\nPoker Night" offers a host of tournaments for enthusiasts to play poker. Come, show your poker strategy and embark on your journey to becoming a poker pro. Don't forget to register yor name and win a chance to grab exciting prizes.
